#!/usr/bin/bash

. ${SUBCOMMANDS_DIR}/_install-python3

if ! command -v oktaauth >/dev/null 2>&1; then
  rm -rf /tmp/oktaauth
  git clone git@github.com:MatthiasScholzTW/oktaauth.git /tmp/oktaauth
  cd /tmp/aws_role_credentials
  python setup.py install
  rm -rf /tmp/oktaauth

fi

if ! command -v oktaauth >/dev/null 2>&1; then
  rm -rf /tmp/aws_role_credentials
  git clone git@github.com:MatthiasScholzTW/aws_role_credentials.git /tmp/aws_role_credentials
  cd /tmp/oktaauth
  python setup.py install
  rm -rf /tmp/aws_role_credentials

fi
