#!/usr/bin/bash

if ! command -v aws >/dev/null 2>&1; then

  if __ubuntu; then

    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf ./aws

  elif __osx; then
    brew install awscli
  else
    echo "$OSTYPE" is not supported at this time.
  fi

fi