#!/usr/bin/bash

if ! command -v go >/dev/null 2>&1; then
  if __ubuntu; then
    sudo wget -q https://golang.org/dl/go1.14.6.linux-amd64.tar.gz -O - | sudo tar zxvf - -C /usr/local

    shellName=$(basename ${SHELL})
    case ${shellName} in

    zsh)
      shellProfileScript="${HOME}/.zshrc"
      ;;

    bash)
      shellProfileScript="${HOME}/.bashrc"
      ;;

    esac

    echo " " >>"${shellProfileScript}"
    echo "export GOROOT=/usr/local/go" >>"${shellProfileScript}"
    echo 'export GOPATH=$HOME/go' >>"${shellProfileScript}"
    echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >>"${shellProfileScript}"

    export GOROOT=/usr/local/go
    export GOPATH=$HOME/go
    export PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH}

    reloadShell() {
      $SHELL -i
    }

    trap reloadShell EXIT


  elif
    __osx
  then
    brew update && brew install golang
  else
    echo "$OSTYPE" is not supported at this time.
  fi

fi
