#!/usr/bin/bash

if [[ ! -z "$ZSH" ]]; then
  if ! command -v z >/dev/null 2>&1; then
    git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
  fi

fi
