#!/usr/bin/bash

os_name=$(uname | tr '[:upper:]' '[:lower:]')

if ! command -v kubectl >/dev/null 2>&1; then

  sudo wget "https://storage.googleapis.com/kubernetes-release/release/v1.16.8/bin/${os_name}/amd64/kubectl" -O /usr/local/bin/kubectl
  sudo chmod +x /usr/local/bin/kubectl

fi

if ! command -v fluxctl >/dev/null 2>&1; then

  sudo wget "https://github.com/fluxcd/flux/releases/download/1.20.0/fluxctl_${os_name}_amd64" -O /usr/local/bin/fluxctl
  sudo chmod +x /usr/local/bin/fluxctl

fi

if ! command -v eksctl >/dev/null 2>&1; then

  wget -qO- "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xvz -C /tmp
  sudo mv /tmp/eksctl /usr/local/bin

fi

if ! command -v helm >/dev/null 2>&1; then
  wget -qO- "https://get.helm.sh/helm-v3.2.4-${os_name}-amd64.tar.gz" | tar xvz -C /tmp
  sudo chmod +x /tmp/"${os_name}"-amd64/helm
  sudo mv /tmp/"${os_name}"-amd64/helm /usr/local/bin
  rm -rf /tmp/"${os_name}"-amd64/
fi
