#!/bin/bash

SUBCOMMAND_DESC="Assume an AWS IAM role."
SUBCOMMAND_HELP=$(
  cat <<EOH

***REMOVED***                      Connect to Trilogy's AWS account.
tw                           Connect to ThoughtWorks' AWS account.
personal                     Connect to my personal AWS account.
time-left                    Print the time remaining in the current assume-role session.

EOH
)

case ${1} in

time-left)

  expiration="$(aws configure get expiration)"
  [[ -z $expiration ]] && exit 1

  secondsRemaining=$(($expiration - $(date -u +%s) - 3))
  date -u -d "@$secondsRemaining" +'%Hh %Mm %Ss'
  [[ $secondsRemaining -ge 0 ]]
  ;;

***REMOVED***)

  set -e

  echo MFA Arn: $(aws configure get serial-number --profile ***REMOVED***)
  echo -n "MFA code: "
  read -s code
  echo

  source $ROOT_DIR/.env3/bin/activate

  temp_role=$(aws --profile ${1} sts assume-role --serial-number $(aws configure get serial-number --profile ***REMOVED***) \
    --role-arn $(aws configure get role-arn --profile ***REMOVED***) --token-code $code \
    --role-session-name AssumedRole --duration-seconds 3600)

  in_green "Assumed admin role.\n"

  expiration=$(echo $temp_role | jq -r .Credentials.Expiration | xargs -I{} date -d {} +%s)
  access_key=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
  secret=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
  token=$(echo $temp_role | jq -r .Credentials.SessionToken)

  in_gray "Expires: $(echo $temp_role | jq -r .Credentials.Expiration | xargs -I{} date -d {}) \n"

  aws configure set aws_session_token $token --profile ***REMOVED***mfa
  aws configure set aws_secret_access_key $secret --profile ***REMOVED***mfa
  aws configure set aws_access_key_id $access_key --profile ***REMOVED***mfa
  aws configure set region us-east-1 --profile ***REMOVED***mfa
  aws configure set expiration $expiration --profile ***REMOVED***mfa

  ;;

tw)

  set -e

  source $ROOT_DIR/.env3/bin/activate
  saml=$(oktaauth --username $(aws configure get username --profile tw)  \
    -s  $(aws configure get server --profile tw) --apptype amazon_aws \
    --appid $(aws configure get tw-app-id --profile tw))

  if [ $? -ne 0 ]; then
    error "Could not authenticate through Okta."
    exit 1
  fi

  in_green "\n\nAuthenticated via Okta.\n"

  echo "$saml" | aws_role_credentials saml --profile tw >/dev/null 2>&1

  if [ $? -ne 0 ]; then
    error "Could not assume role."
    exit 1
  fi

  in_green "Assumed admin federated-admin role.\n"
  expiration=$(($(date +%s) + 3585))
  aws configure set expiration $expiration --profile tw
  in_gray "Expires: $(echo $expiration | xargs -I{} date -d @{}) \n"

  ;;

\
  personal)
  echo "Not implemented."
  ;;
esac
