#!/usr/bin/env bash

SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

***REMOVED***                      Connect to Trilogy's AWS account.
tw                           Connect to ThoughtWorks's AWS account.
personal                     Connect to my personal AWS account.

EOH
)

case ${1} in
  ***REMOVED***)
    shift
    ~/bin/assume-role ***REMOVED*** "$TRILOGY_MFA_ARN" "$TRILOGY_CLIADMINROLE_ARN" ${@}

    tw mfa
  ;;

 tw)

   source $HOME/workspace/.env3.8/bin/activate
    python --version
    saml=`oktaauthpy3 --username ***REMOVED***@thoughtworks.com -s thoughtworks.okta.com --apptype amazon_aws --appid $TW_AWS_APP_ID`
    echo $saml | aws_role_credentials saml --profile tw

    asp tw
  ;;

 personal)
    echo "Hello World!"
  ;;
esac

