#!/usr/bin/env bash

SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

***REMOVED***                      Connect to Trilogy's AWS account.
tw                           Connect to ThoughtWorks's AWS account.
personal                     Connect to my personal AWS account.

EOH
)

#Different actions based on arguments
#Different actions based on arguments
case ${1} in
  ***REMOVED***)
    shift
    ~/bin/assume-role ***REMOVED*** "$TRILOGY_MFA_ARN" "$TRILOGY_CLIADMINROLE_ARN" ${@}
  ;;

 tw)
    echo "Hello World!"
  ;;

 personal)
    echo "Hello World!"
  ;;
esac

