#!/bin/bash

SUBCOMMAND_DESC="Backup WSL file system"
SUBCOMMAND_HELP=$(
  cat <<EOH

start  Backup wsl file system on the Hard Drive

EOH
)

case ${1} in

start)
  rsync --info=name0 --info=progress3 --delete-excluded --exclude="*anaconda*" \
  --exclude="*cache*" --exclude="*.git/*" --exclude=".gnupg" --exclude=".npm" --exclude=".m2" --exclude=".conda" \
  --exclude="go" --archive --delete \
  /home/matiasca/ /e/Dropbox/wsl2_backup
  sleep 10
  ;;
esac



