#!/bin/bash

SUBCOMMAND_DESC="Backup WSL file system"
SUBCOMMAND_HELP=$(
  cat <<EOH

start  Backup wsl file system on the Hard Drive

EOH
)

case ${1} in

start)


  rsync --info=name0 --info=progress3 --archive --delete   \
  /c/Users/Javier/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json \
  $HOME/

  rsync --info=name0 --info=progress3 --delete-excluded --exclude="*anaconda*" \
  --exclude="*cache*" --exclude="*.git/*" --exclude=".gnupg" --exclude=".npm" --exclude=".m2" --exclude=".conda" \
  --exclude="go" --exclude=".env3" --exclude="R/*" --exclude=".theano" --archive --delete \
  /home/matiasca/ /e/Dropbox/wsl2_backup


  ;;
esac



