#!/bin/bash

SUBCOMMAND_DESC="Scan for secret leaks"
SUBCOMMAND_HELP=$(
  cat <<EOH

check -s <pattern_file>  <list_of_files_to_search>                   Check for secret leaks

EOH
)

case ${1} in
check)

  shift #Remove the subcommand from $@

  while getopts ":s:" OPTION; do
    case $OPTION in
    s) patterns=$OPTARG ;;
    *)
      echo $SUBCOMMAND_HELP
      ;;
    esac
  done

  shift $((OPTIND - 1))

  for i in $(echo $patterns | sed "s/,/ /g"); do
    # call your procedure/other scripts here below
    grep -iEn -f $i $@
    status=$?
    if $(exit $status); then
      exit 1
    fi
  done

  ;;

esac
