#!/bin/bash

SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

check  <pattern_file>  <list_of_files_to_search>                   Check for any secret leaks

EOH
)

case ${1} in
  check)
    shift
    patterns=${1}; shift

    grep -Enr -f ~/secret ${@}
    status=$?
    if $(exit $status); then
        exit 1
    fi

    grep -Enr -f ${CONFIGURATION_DIR}/secrets/assume-role/***REMOVED***/mfa-arn ${@}
    status=$?
    if $(exit $status); then
        exit 1
    fi

    grep -Enr -f ${CONFIGURATION_DIR}/secrets/assume-role/***REMOVED***/role-arn ${@}
    status=$?
    if $(exit $status); then
        exit 1
    fi
  ;;

esac

