#!/usr/bin/env bash

SUBCOMMAND_DESC="Install development tools."
SUBCOMMAND_HELP=$(
  cat <<EOH

install eks :  Install tools to assume a role in AWS.
install dev :  Install development tools
install ds  :  Install data science tools.

EOH
)

case ${1} in

install)

  shift
  toolKit=${1}
  shift

  if [ -z $toolKit ]; then
    echo "Must specify a toolkit"
    exit 1
  fi

  case $toolKit in
  eks)

    mypwd=$PWD
    set -e
    clean_up() {
      ARG=$?
      echo "> clean_up"
      rm -rf /tmp/aws_role_credentials
      rm -rf /tmp/oktaauth
      cd $mypwd
      exit $ARG
    }
    trap clean_up EXIT

    . ${SUBCOMMANDS_DIR}/_install-python3
    . ${SUBCOMMANDS_DIR}/_install-okta
    . ${SUBCOMMANDS_DIR}/_install-k8s-tools
    . ${SUBCOMMANDS_DIR}/_install-awscli

    ;;

  dev)

    . ${SUBCOMMANDS_DIR}/_install-python3
    . ${SUBCOMMANDS_DIR}/_install-golang
    . ${SUBCOMMANDS_DIR}/_install-cli-tools

    ;;

  ds)

    . ${SUBCOMMANDS_DIR}/_install-python3
    pip install --upgrade -r ${CONFIGURATION_DIR}/requirements.txt

    ;;

  esac

  ;;

esac
